AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - db/**/*
Layout/IndentHeredoc:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Lint/UnderscorePrefixedVariableName:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 100
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
